# database/migrations/versions/fd9c5e5b4410_add_broker_accounts.py
# database/migrations/script.py.mako

"""add_broker_accounts

Revision ID: fd9c5e5b4410
Revises: 70d535ddf0cb
Create Date: 2026-01-28 00:33:13.031813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9c5e5b4410'
down_revision: Union[str, None] = '70d535ddf0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_name', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('api_key_enc', sa.String(length=500), nullable=False),
    sa.Column('password_enc', sa.String(length=500), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###